export const CONFIG_KEYS = {
  MONTHLY_CONTRIBUTION_AMOUNT: 'MONTHLY_CONTRIBUTION_AMOUNT',
  LOAN_MIN_AMOUNT: 'LOAN_MIN_AMOUNT',
  LOAN_MAX_AMOUNT: 'LOAN_MAX_AMOUNT',
  INTEREST_RATE_SHORT: 'INTEREST_RATE_SHORT',
  INTEREST_RATE_LONG: 'INTEREST_RATE_LONG',
  ELIGIBILITY_MONTHS: 'ELIGIBILITY_MONTHS',
  PAYMENT_DEADLINE_DAY: 'PAYMENT_DEADLINE_DAY',
  PENALTY_TYPE: 'PENALTY_TYPE',
  PENALTY_VALUE: 'PENALTY_VALUE',
  MAX_LOANS_PER_GUARANTOR: 'MAX_LOANS_PER_GUARANTOR',
  EMAIL_PROVIDER: 'EMAIL_PROVIDER',
  EMAIL_FROM_ADDRESS: 'EMAIL_FROM_ADDRESS',
  EMAIL_FROM_NAME: 'EMAIL_FROM_NAME',
  EMAIL_CONTRIBUTION_STATEMENT_CRON: 'EMAIL_CONTRIBUTION_STATEMENT_CRON',
  EMAIL_LOAN_SCHEDULE_ENABLED: 'EMAIL_LOAN_SCHEDULE_ENABLED',
} as const;

export type ConfigKeyString = (typeof CONFIG_KEYS)[keyof typeof CONFIG_KEYS];
