export enum AuditAction {
  Create = 'Create',
  Update = 'Update',
  Delete = 'Delete',
  Import = 'Import',
  Approve = 'Approve',
  Reject = 'Reject',
  Disburse = 'Disburse',
  Settle = 'Settle',
  WriteOff = 'WriteOff',
  RecordPayment = 'RecordPayment',
  GenerateStatement = 'GenerateStatement',
  Download = 'Download',
  Export = 'Export',
  Login = 'Login',
  Logout = 'Logout',
  ConfigChange = 'ConfigChange',
}
